name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          pip install -r flask-app/requirements.txt

      - name: Docker Build & Push
        uses: docker/build-push-action@v4
        with:
          context: flask-app
          push: true
          tags: your-dockerhub-username/flask-app:latest

      - name: Deploy with Helm
        run: |
          helm upgrade --install flask-app flask-app/helm --kubeconfig $(terraform output -raw kubeconfig)
